CREATE OR REPLACE FUNCTION FUNC_FOLHA (pmes in number, pano in number)
  RETURN NUMBER
  IS
    RETORNO NUMBER;
    VSEQ NUMBER;
    VANOMES VARCHAR2(10);
    VINSS FOLHA_PGTO_ITEM.INSS%TYPE;
    VSALLIQ FOLHA_PGTO_ITEM.SALARIOLIQUIDO%TYPE;    
  BEGIN
    IF PMES >= 1 AND PMES <= 12 THEN
      SELECT SEQ_FOLHA.NEXTVAL INTO VSEQ FROM DUAL;
      VANOMES := TO_CHAR(PMES) || TO_CHAR(PANO);
      INSERT INTO FOLHA_PGTO (ID_FOLHA, MESANO, DATAHORAGERACAO)
      VALUES (VSEQ, VANOMES, SYSDATE);
        FOR RS IN (SELECT ID, SALARIO FROM FUNCIONARIO WHERE ATIVO ='S')
        LOOP
          VINSS := RS.SALARIO * 0.11;
          VSALLIQ := RS.SALARIO-VINSS;
          INSERT INTO FOLHA_PGTO_ITEM (ID_FOLHA, ID, SALARIO, INSS, SALARIOLIQUIDO)
          VALUES (VSEQ, RS.ID, RS.SALARIO, VINSS, VSALLIQ);
        END LOOP;
    
    
      RETORNO := 0;
    ELSE
      RETORNO := 1;
      
    END IF;
  COMMIT;
  RETURN RETORNO;
END;