create or replace 
FUNCTION FUCN_TIPOPROD_2 (PID IN NUMBER, PNOME IN VARCHAR2, PATIVO IN CHAR)

  RETURN NUMBER
IS
  RETORNO NUMBER;
  QTDE NUMBER (1);
  NCODTP TIPOPROD.ID_TP%TYPE;
  VSITUA TIPOPROD.ATIVO%TYPE;
BEGIN
  VSITUA := UPPER(PATIVO);
  SELECT COUNT (*) INTO QTDE FROM TIPOPROD WHERE  ID_TP = PID;
    IF QTDE = 1 THEN
      IF LENGTH (PNOME) <= 120 THEN
        IF (VSITUA = 'S' OR VSITUA = 'N') AND LENGTH (VSITUA) = 1 THEN
          SELECT COUNT (*) INTO QTDE FROM TIPOPROD WHERE UPPER(NOME) = UPPER (PNOME) AND ID_TP <> PID;
          IF QTDE = 0 THEN
            UPDATE TIPOPROD SET NOME = PNOME, ATIVO = VSITUA
            WHERE ID_TP = PID;
            RETORNO := 0;
          ELSE
            RETORNO := 1003;
          END IF;
        ELSE
        RETORNO := 1002;
        END IF;
      ELSE
        RETORNO := 1001;
      END IF;
    ELSE
      RETORNO := 1000;
    END IF;
  COMMIT;
  RETURN RETORNO;
END;