create or replace 
FUNCTION FUCN_TIPOPROD (PNOME IN VARCHAR2, PATIVO IN CHAR)

  RETURN NUMBER
IS
  RETORNO NUMBER;
  QTDE NUMBER (1);
  NCODTP TIPOPROD.ID_TP%TYPE;
  VSITUA TIPOPROD.ATIVO%TYPE;
BEGIN
  VSITUA := UPPER(PATIVO);
    IF LENGTH (PNOME) <= 120 THEN
      IF (VSITUA = 'S' OR VSITUA = 'N') AND LENGTH (VSITUA) = 1 THEN
        SELECT COUNT (*) INTO QTDE FROM TIPOPROD WHERE UPPER(NOME) = UPPER (PNOME);
        IF QTDE = 0 THEN
          SELECT MAX(ID_TP)+1 INTO NCODTP FROM TIPOPROD;
            IF NCODTP IS NULL THEN NCODTP := 1;
            END IF;
          INSERT INTO TIPOPROD (ID_TP, NOME, ATIVO)
          VALUES (NCODTP, PNOME, VSITUA);
          RETORNO := 0;
        ELSE
          RETORNO := 1003;
        END IF;
      ELSE
      RETORNO := 1002;
      END IF;
    ELSE
      RETORNO := 1001;
    END IF;
  COMMIT;
  RETURN RETORNO;
END;